### ISSUE TITLE
Error in evaluation

### ISSUE THREAD

**Issue by zhongzho** [OpenNMT/OpenNMT#453] opened 2017-12-10 00:58 UTC
There is an error in the evaluation of the English German training: 
~/torch/install/bin/luajit: ./tools/utils/normalizer.lua:20: attempt to concatenate field 'cmd' (a nil value)

Any thoughts on 'cmd'? Thanks!

**Comment by jsenellart** [comment] 2017-12-10 09:22
this is likely to be a duplicate of #450 for which fix is coming

**Closed by jsenellart** 2017-12-10 09:22 UTC
Labels: duplicate
