### ISSUE TITLE
NMT, What if we do not pass input for decoder?

### ISSUE THREAD

**Issue by guotong1988** [OpenNMT/OpenNMT#575] opened 2019-09-16 06:55 UTC
For transformer-based neural machine translation (NMT), take English-Chinese for example, we pass English for encoder and use decoder input(Chinese) attend to encoder output,  then final output.

What if we do not pass input for decoder and consider it as a 'memory' model for translation. Is it possible and what will happen?

It seems decoder could be removed and there only exist encoder.

Thank you！

**Comment by guillaumekln** [comment] 2019-09-16 07:28
Duplicate of https://github.com/OpenNMT/OpenNMT-tf/issues/494

**Closed by guillaumekln** 2019-09-16 07:28 UTC
